### ISSUE TITLE
Duplicated Tap Dance Name

### ISSUE THREAD

**Issue by perfectbogus** [perryfranks/zmk_corne_prog_dvorak#1]
Hi Perry :-)

First of all, thanks for this config.

Issue:
The tap_dance_7 is duplicated in the corne.keymap between lines 119 and 132
In the latest version of zmk compiler is causing errors:

-- Found devicetree overlay: /__w/zmk-config/zmk-config/config/corne.keymap
devicetree error: /__w/zmk-config/zmk-config/config/corne.keymap:126 (column 26): parse error: /behaviors/tap_dance_7: duplicate node name
CMake Error at /__w/zmk-config/zmk-config/zephyr/cmake/modules/dts.cmake:230 (message):
  gen_defines.py failed with return code: 1

Fix: Just remove it. :-)

**Comment by perryfranks** [comment]
Hi, sorry for the very late fix and thank you for the explicit message. This should be fixed now in master.
